{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "key-server.fullname" . }}
  labels:
    {{- include "key-server.labels" . | nindent 4 }} # Corrected from key-server-app.labels
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
